{{- if .Values.autoscaling.vpa.enabled }}
{{- if eq .Values.misc.istio.deploymentType.abTesting.enabled true }}
{{- range $idx, $node := .Values.misc.istio.deploymentType.abTesting.deployments }}
{{- with $ -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "gx-prueba.fullname" . }}-v{{ $node.name }}
  labels:
    {{- include "gx-prueba.labels" . | nindent 4 }}
      {{- include "gx-prueba.abTestingLabels" $node | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gx-prueba.fullname" . }}-v{{ $node.name }}
  updatePolicy:
    updateMode: "Off"
---
{{- end }}
{{- end }}
{{- else }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "gx-prueba.fullname" . }}
  labels:
    {{- include "gx-prueba.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gx-prueba.fullname" . }}
  updatePolicy:
    updateMode: "Off"
{{- end }}
{{- end }}
