replicaCount: 1
image:
  repository: 758563266136.dkr.ecr.us-east-1.amazonaws.com/gx-prueba
  pullPolicy: IfNotPresent
  containerPort: 3000
  env:
    - name: API_URL
      value: "https://parks.api.xcaret.com/api/v1"
    - name: API_URL_HOTEL
      value: "https://hotels.api.xcaret.com/api/v1"
    - name: S3_URL
      value: "/assets"
    - name: API_CMS_URL
      value: "https://api-cms.ci.xcaret.com/api/v1"
    - name: CMS_URL_VERSION
      value: "/cms/content"
    - name: NODE_ENV
      value: "production"
    - name: SITE_CODE
      value: "XC"
    - name: REDIS_PREFIX
      value: "gx-parques"
    - name: ELASTIC_SEARCH_API
      value: ""
    - name: ELASTIC_SEARCH_KEY
      value: ""
    - name: ELASTIC_SEARCH_ENGINE_NAME
      value: ""
    - name: PORT
      value: 3000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  hosts:
    - host: "pruebagithubaction..xcaret.com"
      paths: ["/"]
  annotations:
    kubernetes.io/ingress.class: "nginx"

resources:
  limits:
    cpu: 200m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 250Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
  vpa:
    enabled: true

misc:
  tolerations:
    enabled: true
  affinity:
    enabled: true
  istio:
    enabled: true
    version: 1
    defaultPolicy:
      defaultDeny: false
      mtlsMode: DISABLE

    authorizations:
      enabled: false
      rules:
      - allowPrincipals:
        - namespace/serviceAccount
        paths:
        - /*

    overallTimeout: 180s
    retries:
      attempts: 3
      perTryTimeout: 60s

    outlierDetection:
      consecutive5xxErrors: 0

    ingressGateway:
      enabled: false
      name: istio-system/istio-gateway
      host: my.gateway.com
      matchPrefix:
        - /
    deploymentType:
      abTesting:
        enabled: false
        deployments:
        - name: "1"
          env:
            - name: BOOKING_VUELO
              value: "v1"
          weight: 100
        - name: "2"
          env:
            - name: BOOKING_VUELO
              value: "v2"
          weight: 0
livenessProbe:
  httpGet:
    path: /healthcheck
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthcheck
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

nodeSelector: {}

tolerations:
  - key: "node.xcaret.com/misc"
    operator: "Equal"
    value: "instana-monitoring"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node.xcaret.com/misc
            operator: In
            values:
            - instana-monitoring
