name: Deploy to ECR
on: push
permissions:
  id-token: write
  contents: write 
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Checkout code
      uses: actions/checkout@v3
       
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::808552883102:role/comercial_github_actions_role_policy
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: gx-prueba
        IMAGE_TAG: main-${{ steps.commit.outputs.short }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      working-directory: ./app
  
    - name: Update kube config
      run: 

    - name: Deploy to EKS
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }} 
        REPOSITORY: gx-prueba       
        IMAGE_TAG: main-${{ steps.commit.outputs.short }}
      run: | 
        aws eks update-kubeconfig --region us-east-1 --name comercial-prod-gx-comercial-prod-cluster
        kubectl set image deployment/gx-prueba gx-prueba=${{ steps.login-ecr.outputs.registry }}:main-${{ steps.commit.outputs.short }}


