name: Deploy to ECR
on: push
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.21.0'
      id: install
       
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::808552883102:role/comercial_github_actions_role_policy
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: gx-prueba
        IMAGE_TAG: main-${{ steps.commit.outputs.short }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks --region us-east-1 update-kubeconfig --name comercial-prod-gx-eks-master-cluster --version 1.21 --approve

    - name: Deploy to EKS
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
        IMAGE_TAG: main-${{ steps.commit.outputs.short }}
      run: |
        aws sts get-caller-identity
        eksctl utils write-kubeconfig --cluster test-cluster -p eksctl
        kubectl apply -f .helm/chart/templates/deployment.yaml
        kubectl apply -f .helm/chart/templates/service.yaml

